name: Build and Release APK

on:
  push:
    branches:
      - release  # Trigger on pushes to the release branch

permissions:
  contents: write  # Ensure the token can create a release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: Spendit
          path: app/build/outputs/apk/debug/app-debug.apk

      # Step 5: Verify APK path (adjust based on your build)
      - name: Verify APK path
        run: ls app/build/outputs/apk/debug/app-debug.apk

      # Step 6: Create a GitHub Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: "Release v1.0.0"
          draft: false
          prerelease: false

      # Step 7: Upload APK to Release
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
